services:
  postgres:
    image: postgres:18.2
    environment:
      POSTGRES_PASSWORD: postgres

  django:
    build: dockerfiles/django
    volumes:
      - ./src:/app/src
    entrypoint: ["/app/entrypoint.sh"]
    depends_on:
      - postgres

  nginx:
    image: nginx:1.29
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src/static:/static
    ports:
      - "80:80"
    depends_on:
      - django
